name: Publication

on: push

jobs:
  build-image:
    name: Construction de l'image Docker
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package.json
          prop_path: version
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          release_name: Release ${{ steps.version.outputs.prop }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/website
          tag_with_ref: true
